AllCops:
  TargetRubyVersion: 2.7
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'spec/**/*'

Layout/EndOfLine:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Exclude:
    - 'lib/languages/languages.rb'
  Max: 20

Style/IfUnlessModifier:
  Exclude:
    - 'lib/**/*'

Style/RaiseArgs:
  Exclude:
    - 'lib/habluhablu.rb'

Style/IfWithBooleanLiteralBranches:
  Exclude:
    - 'lib/languages/languages.rb'

Lint/ScriptPermission:
  Exclude:
    - 'bin/console'

Metrics/ClassLength:
  Exclude:
    - 'lib/languages/languages.rb'

Style/OptionalBooleanParameter:
  Exclude:
    - 'lib/languages/languages.rb'